title: Rifki Afina Putri
position: Ph.D. Candidate
affiliation: KAIST
email: rifkiaputri (at) kaist.ac.kr
google_scholar: https://scholar.google.com/citations?hl=en&user=FsBF4xwAAAAJ
github_link: https://github.com/rifkiaputri
linkedin: https://linkedin.com/in/rifki-afina-putri-73692a6b
avatar: ./assets/img/kiki.jpg
description: Rifki Afina Putri's homepage.
remote_theme: yaoyao-liu/minimal-light
